title: Sea the Difference - Explore maritime career opportunities
url: https://www.seathedifference.gov.sg
favicon: /images/sea_the_difference_insignia__BLUE.png
colors:
  primary-color: "#00838f"
  secondary-color: "#00aaff"
  media-colors:
    - title: media-color-one
      color: "#f0a528"
    - title: media-color-two
      color: "#0000aa"
    - title: media-color-three
      color: "#23aa46"
    - title: media-color-four
      color: "#f0a528"
    - title: media-color-five
      color: "#0f8ce6"
description: ""
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d1gd0hiaqdc0wr.amplifyapp.com
prod: https://master.d1gd0hiaqdc0wr.amplifyapp.com
facebook-pixel: ""
shareicon: /images/maritime_and_port_authority_of_singapore_(logo).png
is_government: true
google_analytics: ""
google_analytics_ga4: G-1JLZMKZMMK
linkedin-insights: "5609004"
resources_name: resources
